### ISSUE TITLE
Does not render Css and javaScript files

### ISSUE THREAD

**Issue by nipsalvin** [dkarchmer/django-aws-template#4]
![127 0 0 1:8000 console](https://user-images.githubusercontent.com/68748209/147054147-2b49148b-943c-450f-8ab9-87ef24a76137.png)

**Comment by dkarchmer** [comment]
Just to confirm, did you build the static files as described before running the server?

**Comment by nipsalvin** [comment]
i followed the instructions on the  README.md file.
Could my issue be  that i haven't properly set up services on aws ?

**Comment by nipsalvin** [comment]
could you please send me a screenshot of how its supposed to work

**Comment by dkarchmer** [comment]
You need to do

```
inv build-statics
inv run-local -a collectstatics
```

and confirm you got no errors. Then you can run the server with

```
inv run-local -a up
```

I won't have time to reproduce for several days, so if you want a screenshot, you will have to wait

**Comment by nipsalvin** [comment]
[image: 127.0.0.1 8000.png]
[image: 127.0.0.1 login.png]
Is this how the final production supposed to look?

**Comment by dkarchmer** [comment]
> [image: 127.0.0.1 8000.png] [image: 127.0.0.1 login.png] Is this how the final production supposed to look?

You didn't include the images correctly

**Comment by dkarchmer** [comment]
This is how it should look. Everything should work if you follow the instructions

![django-aws-template-running](https://user-images.githubusercontent.com/3330496/147711554-89b360fe-5500-4e7e-bcb4-e52c351a4896.png)
